import React, { useState, useEffect, FC } from "react";

import { Loader, Card, FormField } from "../components";

type RenderCardsProps = {
  data: any;
  title: string;
};

const RenderCards: FC<RenderCardsProps> = ({ data, title }) => {
  if (!data || data.length <= 0)
    return (
      <h2 className="mt-5 font-bold text-[#6449ff] text-xl uppercase">
        {title}
      </h2>
    );

  return (
    <>
      {data.map((post: any) => (
        <Card key={post._id} {...post} />
      ))}
    </>
  );
};

const Home = () => {
  const [allPosts, setAllPosts] = useState([]);
  const [loading, setLoading] = useState(false);
  const [searchText, setSearchText] = useState("");

  useEffect(() => {
    try {
      setLoading(true);
      fetch("http://localhost:3000/api/posts/all")
        .then((res) => res.json())
        .then((data) => {
          setAllPosts(data.reverse());
        });
    } catch (error) {
      console.log(error);
    } finally {
      setLoading(false);
    }
  }, []);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { value } = e.currentTarget;
    setSearchText(value);
  };

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="text-[#222328] font-extrabold text-[32px]">
          The Community Showcase
        </h1>
        <p className="mt-2 text-[#666e75] text-[16px] max-w-[500px]">
          Browse through a collection of imaginative and visually stunning
          images generated by the DALL-E AI
        </p>
      </div>

      <div className="mt-16">
        <FormField
          type="text"
          name="search"
          labelName="Search"
          value={searchText}
          placeholder="Search for a post"
          handleChange={handleChange}
        />
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-[#666e75] text-xl mb-3">
                Showing results for{" "}
                <span className="text-[#222328]">{searchText}</span>
              </h2>
            )}

            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards data={[]} title="No search results found" />
              ) : (
                <RenderCards data={allPosts} title="No posts found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
